working on receive-package implementation

diff --git a/server-bin/receive-package b/server-bin/receive-package
--- a/server-bin/receive-package
+++ b/server-bin/receive-package
@@ -1,7 +1,48 @@
 #!/usr/bin/env bash
 
+err() {
+  local mesg="$1"; shift
+  printf "\033[1;31m (remote)error:\033[0;0m ${mesg}\n" "$@" >&2
+  exit 1
+}
+
+msg() {
+  local mesg="$1"; shift
+  printf "\033[1;32m (remote)***\033[0;0m ${mesg}\n" "$@"
+}
+
 user="$1"
 
-echo "Functionality not implemented yet"
+cleanup() {
+  if [[ -n "$path" ]]; then
+    rm -rf "$path"
+  fi
+  exit 1
+}
+
+# when the client disconnects our parent dies and we recieve this signal
+# so start the cleanup process
+trap cleanup SIGHUP
+
+template="${HOME}/uploads/${user}"
+path=$(mktemp -d "${template}")
+if (( $? != 0 )); then
+  err "failed to create directory"
+  exit 1
+fi
+
+
+msg "receiving files..."
+bsdtar -C "${path}" -xvf - <&0 &
+pid=$!
+exec 0>&-
+wait "${pid}"
+if (( $? != 0 )); then
+  err "failed to unpack received data"
+  cleanup
+  exit 1
+fi
+
+msg "Functionality not implemented yet"
 
 # vim: set ts=2 sts=2 sw=2 et:
