nicer output

diff --git a/server-bin/receive-package b/server-bin/receive-package
--- a/server-bin/receive-package
+++ b/server-bin/receive-package
@@ -2,13 +2,13 @@
 
 err() {
   local mesg="$1"; shift
-  printf "\033[1;31m (remote)error:\033[0;0m ${mesg}\n" "$@" >&2
+  printf " (remote) \033[1;31merror:\033[0;0m ${mesg}\n" "$@" >&2
   exit 1
 }
 
 msg() {
   local mesg="$1"; shift
-  printf "\033[1;32m (remote)***\033[0;0m ${mesg}\n" "$@"
+  printf " (remote) \033[1;32m***\033[0;0m ${mesg}\n" "$@"
 }
 
 user="$1"
