user-lib/common updates

diff --git a/user-bin/repo-command.in b/user-bin/repo-command.in
--- a/user-bin/repo-command.in
+++ b/user-bin/repo-command.in
@@ -1,6 +1,9 @@
 #!/usr/bin/env bash
 
-source "%%LIBDIR%%/absd-utils/common.bash" || exit 1
+if ! source "%%LIBDIR%%/absd-utils/common.bash"; then
+  echo 'failed to load absd-utils library'
+  exit 1
+fi
 
 usage() {
   cat <<EOF
